#!/usr/bin/perl

use warnings;
use strict;

use YAML qw( LoadFile );

# Load config
my $config = LoadFile('config.yaml');

# Get name of test run
my $test_name;
if ($config->{debug}) {
    $test_name = 'debug_test';
}
else {
    $test_name = <STDIN>;
    chomp $test_name;
}
chomp $test_name;
print "Running test '$test_name'\n";

my $approx_throughput = get_approx_throughput();

# Copy a small file to compute approximate thoughput
sub get_approx_throughput {
    print "Running a quick benchmark test";

}

# Generate a file of a given size (in megabytes)
# Files will eventually be pseudorandom to prevent compression
# Returns filename
sub generate_file {
    my $size = shift;

    my $filename = "$size.benchmark";

    open(my $fh, '>', $filename);
    # 1024 bytes in a kilobyte, 1024 kilobytes in a megabyte
    print $fh 'x' x (1024 * 1024 * $size);
    close($fh);

    return $filename;
}

# Cleans up a given file by erasing it
sub remove_file {
    my $filename = shift;
}
